#!/bin/bash -e

pkgdir="$1"
stat_f="$2"
pkgname="s-util"
gitroot='git://github.com/yuyichao/s-util.git'

scptdir=$(cd -P $(dirname "${BASH_SOURCE}") && pwd)

cd "$pkgdir"

pkgdir="$PWD"

{
    read predate
    read prerel
    read presec
    read prever
} < "${stat_f}"

if [[ -d "${pkgdir}/src/${pkgname}" ]] ;then
    cd "${pkgdir}/src/${pkgname}" &&
    git checkout master &&
    git pull orgin
else
    mkdir -p "${pkgdir}/src"
    cd "${pkgdir}/src"
    git clone "${gitroot}"
    cd "${pkgname}"
fi

git checkout master

nwst_tg=$(git tag -l | tail -1)
nwst_dt=$(git log --pretty=format:%ct -1)

((day = nwst_dt / 86400))

curdate=$(date +%Y%m%d)

_mkinstl()
{
    local pkgdir="$1" srcdir="$2"
    cat > "${pkgdir}/s-util.install" <<EOF
post_install()
{
$(${srcdir}/install --post_instl)
post_instl /etc/bash.bashrc /usr/bin
}
pre_remove()
{
$(${srcdir}/install --pre_rm)
pre_rm /usr/share/sutil
}
EOF
}

if [[ "$presec" < "$nwst_dt" ]] ;then
    if [[ ${predate} == ${curdate} ]] ;then
	((currel = prerel + 1))
    else
	((currel = 1))
    fi
    mkdir -p "${pkgdir}/pkg-git"
    cd
    {
	echo "pkgver=${curdate}"
	echo "pkgrel=${currel}"
	cat
    } < "${scptdir}/_PKGBUILD-git" > "${pkgdir}/pkg-git/PKGBUILD"
    _mkinstl "${pkgdir}/pkg-git" "${pkgdir}/src/${pkgname}"
    cd "${pkgdir}/pkg-git"
    makepkg --source
    aurup "${pkgname}-git-${pkgver}-${pkg-rel}.pkg.tar.gz"
    cd "${pkgdir}/src/${pkgname}"
else
    currel="$prerel"
    curdate="$predate"
    nwst_dt="$presec"
fi

if [[ "$nwst_tg" != "$prever" ]] ;then
    git checkout "${nwst_tg}"
fi


[[ $mkpkg_git == 1 ]] && {
    {
	echo "pkgver=${pkgver}"
	echo "pkgrel=${pkgrel}"
	cat
    } < "${s_srcdir}/_PKGBUILD-git" > "${currentdir}/PKGBUILD"
    _mkinstl "${currentdir}"
    exit
}

cat > "${varlst}" <<EOF
${_S_INSTALL_DIST}
${_S_BASH_RC}
EOF
