#!/bin/bash

pkgrel=1
pkgdesc="Desktop Utility to open url files, git version"
arch=('any')
url="https://github.com/yuyichao/urlol"
license=('GPL3')
depends=('desktop-file-utils' 'xdg-utils')

package()
{
    cd "${srcdir}/${_fname}"
    ./install -p "$pkgdir" --nopost
}