#!/bin/bash -e

pkgname="hybrid-im"
gitname="hybrid"
cate="network"
pkgdir="$1"
stat_f="$2"
HEAD='
#Maintainer: Yichao Yu <yyc1992@gmail.com>
#Contributor: Yichao Yu <yyc1992@gmail.com>
'
_gitroot='https://github.com/levin108/hybrid.git'




git checkout master

nwst_tg=$(git tag -l | tail -1)
nwst_dt=$(git log --pretty=format:%ct -1)

((day = nwst_dt / 86400))

curdate=$(date -d @${nwst_dt} -u +%Y%m%d)

if [[ "$presec" < "$nwst_dt" ]] ;then
    if [[ ${predate} == ${curdate} ]] ;then
        ((currel = prerel + 1))
    else
        ((currel = 1))
    fi
    mkdir -p "${pkgdir}/pkg-git"
    {
        echo "$HEAD"
        echo "pkgname=${pkgname}-git"
        echo "pkgver=${curdate}"
        echo "pkgrel=${currel}"
        cat | sed -e '/^#!/d'
    } < "${scptdir}/_PKGBUILD-git" > "${pkgdir}/pkg-git/PKGBUILD"
    cd "${pkgdir}/pkg-git"
    makepkg --source
    aurup "${pkgname}-git-${curdate}-${currel}.src.tar.gz" "$cate"
    rm "${pkgname}-git-${curdate}-${currel}.src.tar.gz" PKGBUILD
    cd "${pkgdir}/src/${gitname}"
else
    currel="$prerel"
    curdate="$predate"
    nwst_dt="$presec"
fi

if [[ "$nwst_tg" != "$prever" ]] ;then
    git checkout "${nwst_tg}"
fi

{
    echo "$curdate"
    echo "$currel"
    echo "$nwst_dt"
    echo "$nwst_tg"
} > "${stat_f}"
